baseURL = 'https://www.drlosi.com/henkel-aerospace-distributor/'
title = 'Henkel - Aerospace distributor'

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "EN"
    weight = 1
  [languages.it]
    languageName = "IT"
    weight = 2