baseURL = 'https://www.drlosi.com/henkel-aerospace-distributor/'
title = 'Henkel - Aerospace distributor'

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "ENG"
    weight = 1
  [languages.it]
    languageName = "ITA"
    weight = 2